version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env

  sentiment-aware-chunking:
    image: sentiment-aware-chunking
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    env_file:
      - ./.env

volumes:
  db:
    driver: local
